### ISSUE TITLE
NPE running score command

### ISSUE THREAD

**Issue by mikeylive** [fidildev/fettle#87]
Running `score -o fidildev -r fettle` produces:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at dev.fidil.fettle.handler.GitHubFettleHandler.score(GitHubFettleHandler.kt:141)
	at dev.fidil.fettle.command.ScoreCommand.processCommand(ScoreCommand.kt:9)
	at dev.fidil.fettle.command.FettleCommand.execute(FettleCommand.kt:13)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
	at dev.fidil.fettle.FettleApplicationKt.main(FettleApplication.kt:54)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Date.getTime()" because "this.published_at" is null
	at org.kohsuke.github.GHRelease.getPublished_at(GHRelease.java:161)
	at dev.fidil.fettle.handler.GitHubFettleHandler.deploymentFrequency(GitHubFettleHandler.kt:111)
	... 10 more
```

Debug output shows that there is a release that looks like:

```
GHRelease@2ece4966[assets=[GHAsset@37bd68c3[owner=<null>,name=fettle-85.merge.tar.gz,label=,state=uploaded,size=6390997,url=https://api.github.com/repos/fidildev/fettle/releases/assets/107626321,id=107626321,nodeId=RA_kwDOIbdb584Gaj9R,createdAt=2023-05-11T03:02:59Z,updatedAt=2023-05-11T03:03:00Z], GHAsset@60f7cc1d[owner=<null>,name=fettle-85.merge.zip,label=,state=uploaded,size=6394069,url=https://api.github.com/repos/fidildev/fettle/releases/assets/107626322,id=107626322,nodeId=RA_kwDOIbdb584Gaj9S,createdAt=2023-05-11T03:03:00Z,updatedAt=2023-05-11T03:03:01Z]],name=v85/merge,body=,draft=true,prerelease=false,url=https://api.github.com/repos/fidildev/fettle/releases/102567373,id=102567373,nodeId=RE_kwDOIbdb584GHQ3N,createdAt=2023-05-11T03:02:59Z,updatedAt=<null>]
```

Because this release is a draft it does not have a published_at date.

**Comment by tylerkron** [comment]
@mikeylive - This is odd.

If I run it via the command line I get the NPE too. If I run it via IntelliJ it works just fine. 🤔 

I'll dig into this

**Comment by mikeylive** [comment]
> @mikeylive - This is odd.
> 
> If I run it via the command line I get the NPE too. If I run it via IntelliJ it works just fine. 🤔
> 
> I'll dig into this

What does your IDEA command and environment look like? I get NPE in both cases.

**Comment by tylerkron** [comment]
> What does your IDEA command and environment look like? I get NPE in both cases.

<img width="1040" alt="image" src="https://github.com/fidildev/fettle/assets/6320493/a7fef44f-4f1a-49c9-91c7-9885a0d6b5de">

<img width="1680" alt="image" src="https://github.com/fidildev/fettle/assets/6320493/c6fdcce3-c552-432f-bfcb-87437f6ec9e9">
